#! /bin/bash

# roslaunch hrisim_postprocessing postprocessing.launch bagname:=robotPriority0
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=robotPriority1
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=robotPriority2
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=robotPriority3
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=robotPriority4
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=robotPriority5
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=robotPriority6
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=robotPriority7
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=robotPriority8
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=robotPriority9
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=humanPriority0
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=humanPriority1
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=humanPriority2
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=humanPriority3
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=humanPriority4
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=humanPriority5
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=humanPriority6
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=humanPriority7
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=humanPriority8
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=humanPriority9
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=robotIncrease0
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=robotIncrease1
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=robotIncrease2
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=robotIncrease3
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=robotIncrease4
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=robotIncrease5
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=robotIncrease6
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=robotIncrease7
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=robotIncrease8
# roslaunch hrisim_postprocessing postprocessing.launch bagname:=robotIncrease9

roslaunch bag_postprocess_bringup extract_Goal.launch bagname:=A3
roslaunch bag_postprocess_bringup extract_Goal.launch bagname:=A4
roslaunch bag_postprocess_bringup extract_Goal.launch bagname:=A5
roslaunch bag_postprocess_bringup extract_Goal.launch bagname:=A6
roslaunch bag_postprocess_bringup extract_Goal.launch bagname:=A7
roslaunch bag_postprocess_bringup extract_Goal.launch bagname:=A8
roslaunch bag_postprocess_bringup extract_Goal.launch bagname:=A9
roslaunch bag_postprocess_bringup extract_Goal.launch bagname:=A10
roslaunch bag_postprocess_bringup extract_Goal.launch bagname:=A11
roslaunch bag_postprocess_bringup extract_Goal.launch bagname:=A12
roslaunch bag_postprocess_bringup extract_Goal.launch bagname:=A12
roslaunch bag_postprocess_bringup extract_Goal.launch bagname:=A13
roslaunch bag_postprocess_bringup extract_Goal.launch bagname:=A14
